data:
  type: 'dict'
  required: true
  schema:
    dataset:
      type: 'dict'
      required: true
      schema:
        id:
          type: 'string'
          required: true
        title:
          type: 'string'
          required: true
    source:
      type: 'dict'
      required: true
      schema:
        name:
          type: 'string'
          required: true
        title:
          type: 'string'
          required: true
        url:
          type: 'string'
    processing:
      type: 'string'
      default: 'raw'
    version:
      type: 'string'
      required: true
biodat:
  type: dict
  schema:
    assay:
      type: 'string'
    analysis:
      type: 'string'
    datatype:
      type: 'string'
      required: true
      allowed:
        - 'experimental_dataset'
        - 'analysis_result'
        - 'generic_dataset'
    disease:
      type: 'list'
      schema:
        type: 'string'
    platform:
      type: 'string'
    measurement:
      type: 'string'
    reference:
      type: 'string'
    sample_type:
      type: 'list'
      schema:
        type: 'string'
    species:
      type: 'list'
      schema:
        type: 'integer'
    url:
      type: 'string'
    doi:
      type: 'list'
rows:
  type: 'string'
  required: true
columns:
  type: 'string'
  required: true
styles:
  type: 'dict'
  schema:
    columns:
      type: 'dict'
      schema:
        color:
          type: 'string'
        shape:
          type: 'string'
    rows:
      type: 'dict'
      schema:
        color:
          type: 'string'
        shape:
          type: 'string'
contributors:
  type: 'list'
  schema:
    type: 'dict'
    schema:
      title:
        type: 'string'
      email:
        type: 'string'
      role:
        type: 'string'
provenance:
  type: 'dict'
  schema:
    action:
      type: 'string'
    citations:
      type: 'list'
      schema:
        type: 'string'
    contact:
      type: 'string'
    date:
      type: 'string'
    description:
      type: 'string'
    design:
      type: 'string'
    doc:
      type: 'string'
    software:
      type: 'list'
      schema:
        type: 'dict'
        schema:
          name:
            type: 'string'
          version:
            type: 'string'
    source:
      type: 'string'
    time:
      type: 'string'
    url:
      type: 'string'
    urls:
      type: 'list'
      schema:
        type: 'string'
    version:
      type: 'string'
